### ISSUE TITLE
I had this issue recently on Debian 10, after an update a month or two ago.  I resolved it by modifying the build file with:

### ISSUE THREAD

**Issue by anonbeat** [anonbeat/guayadeque#76]
-DwxWidgets_wxrc_EXECUTABLE='/usr/bin/wxrc' \
 -DwxWidgets_CONFIG_EXECUTABLE='/usr/lib/x86_64-linux-gnu/wx/config/gtk3-unicode-3.0' \
 -DwxWidgets_INCLUDE_DIRS='/usr/include/wx-3.0/'

I am not sure about the Widgets_wxrc_EXECUTABLE, but it launched.  I expect that the version in the Debian repos is still broken.

There are some graphical glitches however, most noticable when closing a tab like Lyrics.  There are also errors on startup:

(guayadeque:14371): Gtk-CRITICAL **: 09:36:47.906: gtk_widget_set_size_request: assertion 'height >= -1' failed

and regular warnings later:

(guayadeque:14371): Gtk-WARNING **: 09:37:07.135: Negative content height -4 (allocation 20, extents 12x12) while allocating gadget (node scale, owner GtkScale)

Given this issue is closed, I can create a new one if it would be preferable.

_Originally posted by @SamDeNies in https://github.com/anonbeat/guayadeque/issues/48#issuecomment-433625343_

**Comment by SamDeNies** [comment]
![screenshot from 2018-10-31 17-59-41](https://user-images.githubusercontent.com/44006848/47823666-51cb0700-dd37-11e8-9b83-86570585a1dc.png)
This is what the graphical glitch looks like after opening and closing the lyrics tab.

**Comment by anonbeat** [comment]
This should be fixed.

**Comment by SamDeNies** [comment]
After installing 4.6-1, this issue is still present.  See the attached screenshot.

You should be aware that I am no longer using Debian 10, but instead ArchLinux.  This issue has been present on Arch since I installed Guayadeque.  If the Lyrics tab is left open, the other tabs work properly, but if Lyrics is closed, the other tabs look like this.

Btw, thank you so very much for continuing to maintain Guayadeque.  It is a great program, and continues to work really well, after all these years.  This issue is really minor to me.

![Screenshot from 2020-05-09 12-20-09](https://user-images.githubusercontent.com/44006848/81480551-12b12800-91f0-11ea-96f7-d8a46348b336.png)

**Comment by anonbeat** [comment]
I think I fixed this a few commits back. Can you confirm the version you are using is after 4 days back ?

**Comment by SamDeNies** [comment]
Ah, confirmed.  I reinstalled from master instead of the latest release version and the issue is gone.

**Comment by SamDeNies** [comment]
I don't know if this is a related issue or not.  I have noticed that in the latest version, the player frame in the top-left does not resize below the width of the button bar (back, stop/play, next, etc).  If the column is narrower, it truncates that frame.  When tabing out and back to guayadeque, the truncated content of the player frame is superimposed on whatever is in the right column.

I understand installing from master is likely to be subject to bugs, since it is basically an alpha, so disregard this if it is still a work in progress.

![Screenshot from 2020-05-10 09-30-32](https://user-images.githubusercontent.com/44006848/81502037-1c469880-92a1-11ea-8c24-01acc46ed7d1.png)

**Comment by anonbeat** [comment]
This last problem should be fixed now with latest commit.

**Comment by SamDeNies** [comment]
Seems to work now.
